package com.convx.music.ui.screens.settings

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.convx.music.R

data class SearchableSetting(
    val title: String,
    val description: String?,
    val category: String,
    val route: String
)

@Composable
fun getAllSearchableSettings(): List<SearchableSetting> {
    return listOf(
        SearchableSetting(stringResource(R.string.about), null, "About", "settings/about"),
        SearchableSetting(stringResource(R.string.account), null, "Account", "settings/account"),
        SearchableSetting(stringResource(R.string.appearance), null, "General", "settings/appearance"),
        SearchableSetting(stringResource(R.string.player_and_audio), null, "General", "settings/player"),
        SearchableSetting(stringResource(R.string.theme), null, "Appearance", "settings/appearance/theme"),
        SearchableSetting("App Font", null, "Appearance", "settings/appearance/font"),
        SearchableSetting("Canvas", null, "Appearance", "settings/appearance/canvas"),
        SearchableSetting("Player Theme", null, "Appearance", "settings/appearance/playertheme"),
        SearchableSetting("Liquid Glass", null, "Appearance", "settings/appearance/liquidglass"),
        SearchableSetting(stringResource(R.string.app_icon), null, "Appearance", "settings/appearance/appicon"),
        SearchableSetting(stringResource(R.string.presets), null, "Appearance", "settings/appearance/presets"),
        SearchableSetting(stringResource(R.string.player_icons), null, "Appearance", "settings/appearance/playericons"),
        SearchableSetting(stringResource(R.string.diy), null, "Appearance", "settings/appearance/diy"),
        SearchableSetting("Equalizer", null, "Player and audio", "settings/equalizer"),
        SearchableSetting(stringResource(R.string.content), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.content_language), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.content_country), null, "Content", "settings/content"),
        SearchableSetting("Suggestions Region", null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.hide_explicit), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.hide_video_songs), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.data_saver_mode), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.hide_youtube_shorts), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.show_artist_description), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.show_artist_subscriber_count), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.show_artist_monthly_listeners), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.show_artist_video), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.show_artist_background_video), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.show_album_canvas), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.app_language), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.network_ip_version), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.enable_proxy), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.config_proxy), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.lyrics_provider_priority), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.lyrics_romanization), null, "Content", "settings/content/romanization"),
        SearchableSetting(stringResource(R.string.randomize_home_order), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.set_quick_picks), null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.playback_logs), null, "Content", "settings/content"),
        SearchableSetting("YouLyPlus", null, "Content", "settings/content"),
        SearchableSetting("PaxSenix", null, "Content", "settings/content"),
        SearchableSetting(stringResource(R.string.modules), null, "Content", "settings/modules"),
        SearchableSetting(stringResource(R.string.ai_lyrics_translation), null, "Content", "settings/ai"),
        SearchableSetting(stringResource(R.string.ai_api_key), null, "AI Lyrics Translation", "settings/ai"),
        SearchableSetting(stringResource(R.string.ai_model), null, "AI Lyrics Translation", "settings/ai"),
        SearchableSetting(stringResource(R.string.ai_provider), null, "AI Lyrics Translation", "settings/ai"),
        SearchableSetting(stringResource(R.string.ai_target_language), null, "AI Lyrics Translation", "settings/ai"),
        SearchableSetting(stringResource(R.string.ai_base_url), null, "AI Lyrics Translation", "settings/ai"),
        SearchableSetting(stringResource(R.string.ai_setup_guide), null, "AI Lyrics Translation", "settings/ai"),
        SearchableSetting("JioSaavn", null, "Player and audio", "settings/player/jio"),
        SearchableSetting(stringResource(R.string.audio_normalization), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.audio_offload), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.audio_quality), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.crossfade), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.crossfade_duration), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.crossfade_gapless), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.auto_download_on_like), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.auto_load_more), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.auto_skip_next_on_error), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.disable_load_more_when_repeat_all), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.persistent_queue), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.pause_music_when_media_is_muted), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.resume_on_bluetooth_connect), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.stop_music_on_task_clear), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.keep_screen_on_when_player_is_expanded), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.history_duration), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.auto_dj_mixing), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.creative_transitions), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.enable_similar_content), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.skip_silence), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.google_cast), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.hide_volume_bar), null, "Player and audio", "settings/player"),
        SearchableSetting(stringResource(R.string.crop_album_art), null, "Appearance", "settings/appearance"),
        SearchableSetting(stringResource(R.string.display_density), null, "Appearance", "settings/appearance"),
        SearchableSetting(stringResource(R.string.grid_card_height), null, "Appearance", "settings/appearance"),
        SearchableSetting(stringResource(R.string.default_lib_chips), null, "Appearance", "settings/appearance"),
        SearchableSetting(stringResource(R.string.default_open_tab), null, "Appearance", "settings/appearance"),
        SearchableSetting(stringResource(R.string.enable_high_refresh_rate), null, "Appearance", "settings/appearance"),
        SearchableSetting(stringResource(R.string.filter_library), null, "Appearance", "settings/appearance"),
        SearchableSetting(stringResource(R.string.privacy), null, "Privacy", "settings/privacy"),
        SearchableSetting(stringResource(R.string.pause_listen_history), null, "Privacy", "settings/privacy"),
        SearchableSetting(stringResource(R.string.pause_search_history), null, "Privacy", "settings/privacy"),
        SearchableSetting(stringResource(R.string.clear_listen_history), null, "Privacy", "settings/privacy"),
        SearchableSetting(stringResource(R.string.clear_search_history), null, "Privacy", "settings/privacy"),
        SearchableSetting(stringResource(R.string.disable_screenshot), null, "Privacy", "settings/privacy"),
        SearchableSetting(stringResource(R.string.storage), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.image_cache), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.song_cache), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.max_image_cache_size), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.max_song_cache_size), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.clear_image_cache), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.clear_song_cache), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.downloaded_songs), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.clear_all_downloads), null, "Storage", "settings/storage"),
        SearchableSetting(stringResource(R.string.backup_restore), null, "Backup & Restore", "settings/backup_restore"),
        SearchableSetting("Import from Spotify", null, "Backup & Restore", "settings/spotify"),
        SearchableSetting("Import from local file", null, "Backup & Restore", "settings/backup_restore"),
        SearchableSetting(stringResource(R.string.integrations), null, "Account", "settings/integrations"),
        SearchableSetting(stringResource(R.string.listen_together), null, "Integrations", "settings/integrations/listen_together"),
        SearchableSetting(stringResource(R.string.yt_sync), null, "Account", "settings/account"),
        SearchableSetting(stringResource(R.string.login), null, "Account", "settings/account"),
        SearchableSetting(stringResource(R.string.advanced_login), null, "Account", "settings/account"),
        SearchableSetting(stringResource(R.string.listenbrainz_scrobbling), null, "Account", "settings/account"),
        SearchableSetting(stringResource(R.string.set_listenbrainz_token), null, "Account", "settings/account"),
        SearchableSetting(stringResource(R.string.more_content), null, "Account", "settings/account"),
        SearchableSetting(stringResource(R.string.history), null, "Activity", "history"),
        SearchableSetting(stringResource(R.string.stats), null, "Activity", "stats"),
    )
}
